### ISSUE TITLE
Docker Compose Misbehavior in EDC Connector with Multiple Participants

### ISSUE THREAD

**Issue by RadZabi** [Data-Cellar/participant-template#9]
I found an issue with the Docker Compose commands in the taskfile when starting or stopping the edc-connector when deploying multi-participant in the same server (eg. consumer and provider)
> Tested with Docker Compose version v2.25.0

We need to add the -p {{.PARTICIPANT_NAME}} flag for proper namespace isolation to both the start and stop tasks in the Taskfile .

```
start:
  desc: "Start the connector stack"
  deps:
    - config
  cmds:
    - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up -d --wait

stop:
  desc: "Stop the connector stack"
  cmds:
    - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml down
```
